/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applicationmedecin;

import entities.Medecin;
import entities.Patient;
import interfaces.SessionBeanAnalysesRemote;
import interfaces.SessionBeanPatientRemote;
import java.util.ArrayList;
import java.util.List;
import javax.ejb.EJB;
import javax.swing.JOptionPane;

/**
 *
 * @author Philippe
 */
public class EntrerPatientForm extends javax.swing.JFrame
{
    @EJB
    private static SessionBeanAnalysesRemote EJBAnalyses;
    @EJB
    private static SessionBeanPatientRemote EJBPatients;
    private final Medecin medecin;
    
    /**
     * Creates new form EntrerPatientForm
     * @param EJBAnalyses
     * @param EJBPatients
     * @param medecin
     */
    public EntrerPatientForm(SessionBeanAnalysesRemote EJBAnalyses, SessionBeanPatientRemote EJBPatients, Medecin medecin)
    {
        EntrerPatientForm.EJBAnalyses = EJBAnalyses;
        EntrerPatientForm.EJBPatients = EJBPatients;
        this.medecin = medecin;
        
        initComponents();       
        setLocationRelativeTo(null);
        
        setTitle("Medecin : " + medecin.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTF_Nom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTF_Prenom = new javax.swing.JTextField();
        jButton_Chercher = new javax.swing.JButton();
        jButton_Ajouter = new javax.swing.JButton();
        jButton_Quitter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Chercher un patient");

        jLabel1.setText("Nom :");

        jTF_Nom.setText("Serrhini");

        jLabel3.setText("Prénom :");

        jTF_Prenom.setText("Souad");

        jButton_Chercher.setText("Chercher");
        jButton_Chercher.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_ChercherActionPerformed(evt);
            }
        });

        jButton_Ajouter.setText("Ajouter un patient");
        jButton_Ajouter.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_AjouterActionPerformed(evt);
            }
        });

        jButton_Quitter.setText("Quitter");
        jButton_Quitter.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_QuitterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_Quitter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Ajouter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Chercher))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTF_Nom)
                            .addComponent(jTF_Prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTF_Nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_Prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Chercher)
                    .addComponent(jButton_Ajouter)
                    .addComponent(jButton_Quitter))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ChercherActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton_ChercherActionPerformed
    {//GEN-HEADEREND:event_jButton_ChercherActionPerformed
        List Patients = EJBPatients.ChercherPatient(jTF_Nom.getText(), jTF_Prenom.getText());
        
        switch(Patients.size())
        {
            case 0:
                JOptionPane.showMessageDialog(this, "Aucun patient trouvé !", "Erreur", JOptionPane.ERROR_MESSAGE);
                break;
            case 1:
                new MedecinForm(EJBAnalyses, EJBPatients, medecin, (Patient) Patients.get(0)).setVisible(true);
                break;
            default:
                new ListePatientsForm(EJBAnalyses, EJBPatients, this, medecin, Patients).setVisible(true);
                break;
        }
    }//GEN-LAST:event_jButton_ChercherActionPerformed

    private void jButton_AjouterActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton_AjouterActionPerformed
    {//GEN-HEADEREND:event_jButton_AjouterActionPerformed
        new AjouterPatientForm(EJBAnalyses, EJBPatients, medecin, this).setVisible(true);
    }//GEN-LAST:event_jButton_AjouterActionPerformed

    private void jButton_QuitterActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton_QuitterActionPerformed
    {//GEN-HEADEREND:event_jButton_QuitterActionPerformed
        String[] options = new String[] {"Oui", "Non"};
        int Choix = JOptionPane.showOptionDialog(null, "Êtes-vous sûr de vouloir quitter ?", "Quitter ?", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);
        
        if(Choix == 0)
        {
            this.dispose();
            System.exit(0);
        }
    }//GEN-LAST:event_jButton_QuitterActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Ajouter;
    private javax.swing.JButton jButton_Chercher;
    private javax.swing.JButton jButton_Quitter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTF_Nom;
    private javax.swing.JTextField jTF_Prenom;
    // End of variables declaration//GEN-END:variables
}
