/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applicationmedecin;


import entities.Medecin;
import entities.Patient;
import interfaces.SessionBeanAnalysesRemote;
import interfaces.SessionBeanPatientRemote;
import java.util.List;
import javax.ejb.EJB;
import javax.jms.Connection;
import javax.jms.Session;
import javax.jms.Topic;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Philippe
 */
public class ListePatientsForm extends javax.swing.JFrame
{
    @EJB
    private static SessionBeanAnalysesRemote EJBAnalyses;
    @EJB
    private static SessionBeanPatientRemote EJBPatients;
    private final Medecin medecin;
    private final EntrerPatientForm mainFrame;
    private final List Patients;    
    
    private final Topic topic;
    private final Connection connection;
    private final Session session;

    /**
     * Creates new form GestionPatientsForm
     * @param EJBAnalyses
     * @param mainFrame
     * @param EJBPatients
     * @param Patients
     * @param medecin
     * @param topic
     * @param connection
     * @param session
     */
    
    public ListePatientsForm(SessionBeanAnalysesRemote EJBAnalyses, SessionBeanPatientRemote EJBPatients, EntrerPatientForm mainFrame, Medecin medecin, List Patients, Topic topic, Connection connection, Session session)
    {
        ListePatientsForm.EJBAnalyses = EJBAnalyses;
        ListePatientsForm.EJBPatients = EJBPatients;  
        this.medecin = medecin;
        this.Patients = Patients;
        this.mainFrame = mainFrame;        
        
        this.topic = topic;
        this.connection = connection;
        this.session = session;
        
        initComponents();
        setLocationRelativeTo(null);
        
        System.out.println("Patients = " + Patients);
        DefaultTableModel dlm = (DefaultTableModel) jTablePatients.getModel();
        Object[][] objects = new Object[Patients.size()][4];
        
        for(int i = 0 ; i < Patients.size() ; i++)
        {
            Patient p = (Patient) Patients.get(i);
            objects[i][0] = p.getIdPatient();
            objects[i][1] = p.getNom();
            objects[i][2] = p.getPrenom();
            objects[i][3] = p.getLogin();
            dlm.addRow(objects[i]);
        }
        jLabel.setText("Selectionnez un patient dans la liste");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePatients = new javax.swing.JTable();
        jButton_Annuler = new javax.swing.JButton();
        jLabel = new javax.swing.JLabel();
        jButton_Ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTablePatients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "idPatient", "Nom", "Prénom", "Login"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jTablePatients.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jTablePatientsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePatients);
        jTablePatients.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTablePatients.getColumnModel().getColumnCount() > 0)
        {
            jTablePatients.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTablePatients.getColumnModel().getColumn(2).setPreferredWidth(200);
        }

        jButton_Annuler.setText("Annuler");
        jButton_Annuler.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_AnnulerActionPerformed(evt);
            }
        });

        jButton_Ok.setText("Ok");
        jButton_Ok.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_OkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 856, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(378, 378, 378)
                        .addComponent(jButton_Annuler)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Ok)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Annuler)
                    .addComponent(jButton_Ok))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_OkActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton_OkActionPerformed
    {//GEN-HEADEREND:event_jButton_OkActionPerformed
        int selectedRow = jTablePatients.getSelectedRow();
        if(selectedRow == -1)
        {
            JOptionPane.showMessageDialog(this, "Aucun patient sélectionné !", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            Patient selectedPatient = (Patient) Patients.get(selectedRow);            
            this.dispose();
            mainFrame.dispose();
            
            new MedecinForm(EJBAnalyses, EJBPatients, medecin, selectedPatient, topic, connection, session).setVisible(true);
        }
    }//GEN-LAST:event_jButton_OkActionPerformed

    private void jButton_AnnulerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton_AnnulerActionPerformed
    {//GEN-HEADEREND:event_jButton_AnnulerActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_AnnulerActionPerformed

    private void jTablePatientsMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jTablePatientsMouseClicked
    {//GEN-HEADEREND:event_jTablePatientsMouseClicked
        if (evt.getClickCount() == 2 && !evt.isConsumed()) 
        {
            int selectedRow = jTablePatients.getSelectedRow();
            Patient selectedPatient = (Patient) Patients.get(selectedRow);            
            this.dispose();
            mainFrame.dispose();
            
            new MedecinForm(EJBAnalyses, EJBPatients, medecin, selectedPatient, topic, connection, session).setVisible(true);
        }
    }//GEN-LAST:event_jTablePatientsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Annuler;
    private javax.swing.JButton jButton_Ok;
    private javax.swing.JLabel jLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePatients;
    // End of variables declaration//GEN-END:variables
}
