/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applicationmedecin;

import entities.Medecin;
import interfaces.SessionBeanAnalysesRemote;
import java.security.Principal;

/**
 *
 * @author Philippe
 */
public class MedecinForm extends javax.swing.JFrame
{
    private final Principal principal;
    private final Medecin medecin;
    private final SessionBeanAnalysesRemote EJBAnalyses;
    /**
     * Creates new form MedecinForm
     * @param principal
     * @param medecin
     * @param EJBAnalyses
     */
    public MedecinForm(Principal principal, Medecin medecin, SessionBeanAnalysesRemote EJBAnalyses)
    {
        this.principal = principal;
        this.medecin = medecin;
        this.EJBAnalyses = EJBAnalyses;
        
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel_Central = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem_ListePatients = new javax.swing.JMenuItem();
        jMenuItem_AjouterPatient = new javax.swing.JMenuItem();
        jMenuItem_ModifierPatient = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel_CentralLayout = new javax.swing.GroupLayout(jPanel_Central);
        jPanel_Central.setLayout(jPanel_CentralLayout);
        jPanel_CentralLayout.setHorizontalGroup(
            jPanel_CentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        jPanel_CentralLayout.setVerticalGroup(
            jPanel_CentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 557, Short.MAX_VALUE)
        );

        jMenu1.setText("Gérer les patients");

        jMenuItem_ListePatients.setText("Liste des patients");
        jMenuItem_ListePatients.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem_ListePatientsActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_ListePatients);

        jMenuItem_AjouterPatient.setText("Ajouter un patient");
        jMenu1.add(jMenuItem_AjouterPatient);

        jMenuItem_ModifierPatient.setText("Modifier un patient");
        jMenu1.add(jMenuItem_ModifierPatient);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Prescrire des analyses");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Consulter les résultats");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Central, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Central, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_ListePatientsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem_ListePatientsActionPerformed
    {//GEN-HEADEREND:event_jMenuItem_ListePatientsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_ListePatientsActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_AjouterPatient;
    private javax.swing.JMenuItem jMenuItem_ListePatients;
    private javax.swing.JMenuItem jMenuItem_ModifierPatient;
    private javax.swing.JPanel jPanel_Central;
    // End of variables declaration//GEN-END:variables
}
