/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applicationpatient;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import ws.Analyses;

/**
 *
 * @author Philippe
 */
public class EntrerReferenceFrame extends javax.swing.JFrame
{

    /**
     * Creates new form EntrerReferenceFrame
     */
    public EntrerReferenceFrame()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jTF_Ref = new javax.swing.JTextField();
        jButton_Voir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Entrer la référence de la demande :");

        jButton_Voir.setText("Voir les résultats");
        jButton_Voir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_VoirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTF_Ref)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButton_Voir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_Ref, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Voir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_VoirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton_VoirActionPerformed
    {//GEN-HEADEREND:event_jButton_VoirActionPerformed
        ws.WsResultat_Service service = new ws.WsResultat_Service();
        ws.WsResultat port = service.getWsResultatPort();
        int Ref;
        try
        {
            Ref = Integer.parseInt(jTF_Ref.getText());
            ArrayList<Analyses> Analyses = (ArrayList<Analyses>) port.getResultats(Ref);

            if(Analyses.isEmpty())
            JOptionPane.showMessageDialog(this, "Les résultats ne sont pas encore disponibles ou alors la référence n'existe pas !", "Attention", JOptionPane.WARNING_MESSAGE);
            else
            {
                new AfficherAnalysesFrame(Ref, Analyses).setVisible(true);
            }
        }
        catch(NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(this, "La valeur entrée n'est pas numérique !", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_VoirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Voir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTF_Ref;
    // End of variables declaration//GEN-END:variables
}
