/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applicationmedecin;

import entities.Patient;
import interfaces.SessionBeanPatientRemote;
import javax.ejb.EJB;

/**
 *
 * @author Philippe
 */
public class ModifierPatientPanel extends javax.swing.JPanel
{
    @EJB
    private static SessionBeanPatientRemote EJBPatients;
    private final MedecinForm medecinForm;
    
    /**
     * Creates new form AjouterPatientForm
     * @param EJBPatients
     * @param medecinForm
     */
    public ModifierPatientPanel(SessionBeanPatientRemote EJBPatients, MedecinForm medecinForm)
    {
        ModifierPatientPanel.EJBPatients = EJBPatients;
        this.medecinForm = medecinForm;
        
        initComponents();
        
        jTF_Nom.setText(medecinForm.getPatient().getNom());
        jTF_Prenom.setText(medecinForm.getPatient().getPrenom());
        jTF_Login.setText(medecinForm.getPatient().getLogin());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel4 = new javax.swing.JLabel();
        jTF_Prenom = new javax.swing.JTextField();
        jTF_Login = new javax.swing.JTextField();
        jButton_Modifier = new javax.swing.JButton();
        jButton_Annuler = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTF_Nom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(614, 393));

        jLabel4.setText("Login :");

        jButton_Modifier.setText("Modifier");
        jButton_Modifier.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_ModifierActionPerformed(evt);
            }
        });

        jButton_Annuler.setText("Annuler");
        jButton_Annuler.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_AnnulerActionPerformed(evt);
            }
        });

        jLabel1.setText("Nom :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Modifier le patient");

        jLabel3.setText("Prénom :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_Annuler)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_Modifier)
                                .addGap(66, 66, 66))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTF_Nom)
                                    .addComponent(jTF_Login)
                                    .addComponent(jTF_Prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(184, 184, 184))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(164, 164, 164))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTF_Nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_Prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTF_Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Modifier)
                    .addComponent(jButton_Annuler))
                .addContainerGap(113, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ModifierActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton_ModifierActionPerformed
    {//GEN-HEADEREND:event_jButton_ModifierActionPerformed
        Patient updatedPatient = new Patient();
        updatedPatient.setIdPatient(medecinForm.getPatient().getIdPatient());
        updatedPatient.setDemandeList(medecinForm.getPatient().getDemandeList());
        updatedPatient.setNom(jTF_Nom.getText());
        updatedPatient.setPrenom(jTF_Prenom.getText());
        updatedPatient.setLogin(jTF_Login.getText());

        EJBPatients.ModifierPatient(updatedPatient);
        medecinForm.setPatient(updatedPatient);
        medecinForm.setTitle("Medecin : " + medecinForm.getMedecin().toString() + " | Patient : " + medecinForm.getPatient().toString());

        medecinForm.jButton_Modifier.setEnabled(true);
        medecinForm.jButton_Prescrire.setEnabled(true);
        medecinForm.jButton_Consulter.setEnabled(true);
        medecinForm.jButton_Quitter.setEnabled(true);
        
        medecinForm.getjPanel().removeAll();
        medecinForm.getjPanel().repaint();
    }//GEN-LAST:event_jButton_ModifierActionPerformed

    private void jButton_AnnulerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton_AnnulerActionPerformed
    {//GEN-HEADEREND:event_jButton_AnnulerActionPerformed
        medecinForm.jButton_Modifier.setEnabled(true);
        medecinForm.jButton_Prescrire.setEnabled(true);
        medecinForm.jButton_Consulter.setEnabled(true);
        medecinForm.jButton_Quitter.setEnabled(true);
        
        medecinForm.getjPanel().removeAll();
        medecinForm.getjPanel().repaint();
    }//GEN-LAST:event_jButton_AnnulerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Annuler;
    private javax.swing.JButton jButton_Modifier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTF_Login;
    private javax.swing.JTextField jTF_Nom;
    private javax.swing.JTextField jTF_Prenom;
    // End of variables declaration//GEN-END:variables
}
