/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applicationmedecin;

import entities.Medecin;
import entities.Patient;
import interfaces.SessionBeanAnalysesRemote;
import interfaces.SessionBeanPatientRemote;
import java.awt.Component;
import java.util.ArrayList;
import javax.ejb.EJB;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Philippe
 */
public class PrescriptionPanel extends javax.swing.JPanel
{
    @EJB
    private static SessionBeanAnalysesRemote EJBAnalyses;
    @EJB
    private static SessionBeanPatientRemote EJBPatients;
    private final Medecin medecin;
    private final Patient patient;
    private final MedecinForm frame;
    /**
     * Creates new form PrescriptionPanel
     * @param EJBAnalyses
     * @param EJBPatients
     * @param medecin
     * @param patient
     * @param frame
     */
    public PrescriptionPanel(SessionBeanAnalysesRemote EJBAnalyses, SessionBeanPatientRemote EJBPatients, Medecin medecin, Patient patient, MedecinForm frame)
    {
        PrescriptionPanel.EJBAnalyses = EJBAnalyses;
        PrescriptionPanel.EJBPatients = EJBPatients;  
        this.medecin = medecin;
        this.patient = patient;
        this.frame = frame;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jButton_Prescrire = new javax.swing.JButton();
        jButton_Annuler = new javax.swing.JButton();
        jCB_Urgent = new javax.swing.JCheckBox();

        setPreferredSize(new java.awt.Dimension(614, 393));

        jLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel.setText("Prescrire une analyse");

        jCheckBox1.setText("Lucocytes");

        jCheckBox2.setText("Hématies");

        jCheckBox3.setText("Hémoglobine");

        jCheckBox4.setText("Hématocrite");

        jCheckBox5.setText("V.G.M.");

        jCheckBox6.setText("C.C.M.H.");

        jCheckBox7.setText("T.C.M.H.");

        jCheckBox8.setText("RDW");

        jButton_Prescrire.setText("Prescrire");
        jButton_Prescrire.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_PrescrireActionPerformed(evt);
            }
        });

        jButton_Annuler.setText("Annuler");
        jButton_Annuler.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_AnnulerActionPerformed(evt);
            }
        });

        jCB_Urgent.setText("Urgent");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jCB_Urgent))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox1)
                                    .addComponent(jCheckBox4)
                                    .addComponent(jCheckBox3)
                                    .addComponent(jCheckBox2))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jCheckBox8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBox5)
                                        .addGap(12, 12, 12)))))))
                .addGap(0, 180, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Annuler)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Prescrire)
                .addGap(238, 238, 238))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel)
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(jCB_Urgent)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Prescrire)
                    .addComponent(jButton_Annuler))
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AnnulerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton_AnnulerActionPerformed
    {//GEN-HEADEREND:event_jButton_AnnulerActionPerformed
        String[] options = new String[] {"Oui", "Non"};
        int Choix = JOptionPane.showOptionDialog(null, "Êtes-vous sûr de vouloir annuler la demande ?", "Annuler ?", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);
        
        if(Choix == 0)
        {            
            frame.jPanel.removeAll();
            frame.jPanel.repaint();

            frame.jButton_Modifier.setEnabled(true);
            frame.jButton_Prescrire.setEnabled(true);
            frame.jButton_Consulter.setEnabled(true);
            frame.jButton_Quitter.setEnabled(true);
        }       
    }//GEN-LAST:event_jButton_AnnulerActionPerformed

    private void jButton_PrescrireActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton_PrescrireActionPerformed
    {//GEN-HEADEREND:event_jButton_PrescrireActionPerformed
        ArrayList<String> la = new ArrayList<>();
        
        Component[] comps = this.getComponents();
        for (Component comp : comps) 
        {
            if(comp instanceof JCheckBox && !((JCheckBox)comp).getText().equals("Urgent") && ((JCheckBox)comp).isSelected())
                la.add(((JCheckBox)comp).getText());
        }
        
        int DemandeId = EJBAnalyses.PrescrireDemande(medecin, patient, jCB_Urgent.isSelected(), la);
        
        frame.jPanel.removeAll();
        frame.jPanel.repaint();
        
        frame.jButton_Modifier.setEnabled(true);
        frame.jButton_Prescrire.setEnabled(true);
        frame.jButton_Consulter.setEnabled(true);
        frame.jButton_Quitter.setEnabled(true);
        
        JOptionPane.showMessageDialog(this, "La demande a bien été créé avec la référence : " + DemandeId + " !", "Information", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton_PrescrireActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Annuler;
    private javax.swing.JButton jButton_Prescrire;
    private javax.swing.JCheckBox jCB_Urgent;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JLabel jLabel;
    // End of variables declaration//GEN-END:variables
}
