/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applicationlaborantin;

import entities.Demande;
import interfaces.SessionBeanAnalysesRemote;
import javax.ejb.EJB;
import javax.jms.Connection;
import javax.jms.JMSException;
import javax.jms.Message;
import javax.jms.MessageConsumer;
import javax.jms.MessageListener;
import javax.jms.MessageProducer;
import javax.jms.ObjectMessage;
import javax.jms.Queue;
import javax.jms.Session;
import javax.jms.TextMessage;
import javax.jms.Topic;

/**
 *
 * @author Philippe
 */
public class LaborantinFrame extends javax.swing.JFrame implements MessageListener
{
    @EJB
    private static SessionBeanAnalysesRemote EJBAnalyses;
    
    private final Queue queue;
    private final Connection connectionQ;
    private final Session sessionQ;    
    
    private final Topic topic;
    private final Connection connectionT;
    private final Session sessionT;

    private MessageProducer producerQ = null;
    private MessageConsumer consumerQ = null;    
    
    private MessageProducer producerT = null;
    private MessageConsumer consumerT = null;
    
    /**
     * Creates new form LaborantinFrame
     * @param EJBAnalyses
     * @param queue
     * @param connectionQ
     * @param sessionQ
     * @param topic
     * @param connectionT
     * @param sessionT
     */
    public LaborantinFrame(SessionBeanAnalysesRemote EJBAnalyses, Queue queue, Connection connectionQ, Session sessionQ, Topic topic, Connection connectionT, Session sessionT)
    {        
        LaborantinFrame.EJBAnalyses = EJBAnalyses;
        this.queue = queue;
        this.connectionQ = connectionQ;
        this.sessionQ = sessionQ;
        this.topic = topic;
        this.connectionT = connectionT;
        this.sessionT = sessionT;
        
        try
        {
            consumerQ = sessionQ.createConsumer(queue);
            consumerQ.setMessageListener((MessageListener) this);
            
            producerQ = sessionQ.createProducer(queue);
            
            
            consumerT = sessionT.createConsumer(topic);
            consumerT.setMessageListener((MessageListener) this);
            
            producerT = sessionT.createProducer(topic);
        }
        catch(JMSException ex)
        {
            ex.printStackTrace();
            System.exit(1);
        }
        
        initComponents();
        setLocationRelativeTo(null);
    }
    
    @Override
    public void onMessage(Message message)
    {
        System.out.println("====== Réception d'une notification de myQueue =====");
        try 
        {
            ObjectMessage om = (ObjectMessage) message;

            if(om.getBooleanProperty("Demande") == true)
            {
                jButton_Traiter.setEnabled(true);

                Demande d = (Demande) om.getObject();
                
            }
        } 
        catch (JMSException ex) 
        {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jButton_Traiter = new javax.swing.JButton();
        jButton_Quitter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_Traiter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_Traiter.setText("Traiter la demande");
        jButton_Traiter.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_TraiterActionPerformed(evt);
            }
        });

        jButton_Quitter.setText("Quitter");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton_Traiter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jButton_Quitter)
                .addContainerGap(167, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(jButton_Traiter, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jButton_Quitter)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_TraiterActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton_TraiterActionPerformed
    {//GEN-HEADEREND:event_jButton_TraiterActionPerformed
        jButton_Traiter.setEnabled(false);
    }//GEN-LAST:event_jButton_TraiterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Quitter;
    private javax.swing.JButton jButton_Traiter;
    // End of variables declaration//GEN-END:variables
}
